services:

  db:
    image: mysql:9.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysqldata: