services:

  backend:
    build:
      context: ./backend/
    ports:
      - 5000:${FLASK_PORT}
    environment:
      # Port
      FLASK_PORT: ${FLASK_PORT}
      # Database configuration
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: products
    depends_on:
      - db
    networks:
      - mynetwork
    
  db:
    image: mysql:9.3.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysqldata: